:toc: left
:toclevels: 5
:sectnums:
:stem:
:source-highlighter: coderay

= 令和1年度 中小企業の診断および助言に関する実務の事例 2

== 背景

=== ドメイン

B社は資本金200万円、社長を含む従業者2名の完全予約制ネイルサロンであり、地方都市X市内の商店街に立地する。この商店街は県内では大規模であり、週末に他地域からも来街客がある。中心部には小型百貨店が立地し、その周辺には小数ではあるが有名ブランドの衣料品店、宝飾店などのファッション関連の路面店が出店している。中心部以外には周辺住民が普段使いするような飲食店や生鮮品店、食料品店、雑貨店、美容室などが出店している。X市は県内でも有数の住宅地であり、中でも商店街周辺は高級住宅地地として知られる。X市では商店街周辺を中核として15年前にファミリー向け住宅の開発が行われ、その頃に多数の家族が入居した（現在の人口分布は4ページの図1参照）。当該地域は新興住宅地であるものの、桜祭り、七夕祭り、秋祭り、クリスマス・マーケットなどの町内会、寺社、商店街主催のイベントが毎月あり、行事が盛んな土地柄である。


B社は2017年に現在の社長が創業した。社長と社員のYさんは共に40代の女性で、美術大学の同級生であり、美大時代に意気投合した友人でもある。社長は美大卒業後、当該県内の食品メーカーに勤務し、社内各部署からの要望に応じて、パッケージ、販促物をデザインする仕事に従事した。特に在職中から季節感の表現に定評があり、社長が提案した季節限定商品のパッケージや季節催事用のPOPは、同社退職後も継続して利用されていた。Yさんは美大卒業後、X市内2店を含む10店舗を有する貸衣裳チェーン店に勤務し、衣装やアクセサリーの組み合わせを提案するコーディネーターとして従事した。2人は同時期の出産を契機に退職し、しばらくは専業主婦として過ごしていた。やがて、子供が手から離れた頃に社長が、好きなデザインの仕事を、家事をこなしながら少ない元手で始められる仕事がないかと思案した結果、ネイルサロンの開業という結論に至った。Yさんも社長の誘いを受け、起業に参加した。なお、Yさんはその時期、前職の貸衣裳チェーン店が予約会（注）を開催し、人手が不足する時期に、パートタイマーの同社店舗スタッフとして働いていた。Yさんは七五三、卒業式、結婚式に参列する30-50代の女性顧客に、顧客の要望を聞きながら、参加イベントの雰囲気に合わせて衣装の提案を行う接客が高く評価されており、同社に惜しまれながらの退職であった。2人は開業前にネイリスト専門学校に通い始めた。当初は絵画との筆遣いに戸惑いを覚えたが、容量を得てからは持ち前の絵心で技術は飛躍的に向上した。

技術を身に着けた2人は、出店候補地の検討を開始した。その過程で空き店舗がみつかり、スペースを改装して、営業を開始した。なお、当該店舗は商店街の中心部からは離れた場所にあり、建築から年数がたっており、細長いスペースが敬遠されていた。そのため、商店街の中では格安の賃貸料で借りることができた。また、デザインや装飾は2人の得意とするところであり、大規模な工事を除く内装のほとんどは手作業で行った。2人で施術すれば満員となるような狭いスペースではあるものの、顧客からは落ち着く雰囲気だと高い評価を得ている。また、Yさんが商店街の貸衣裳チェーン店で勤務していた経緯もあり、商店街の他店ともスムーズに良好な関係を構築することができた。

ネイルサロンとは、ネイル化粧品を用いて手および足の爪にネイルケア、ネイルアートなどを施すサービスを行う店舗を指す。一般にネイルサロンの主力サービスは、ジェルネイルである（4ページの図2参照）。ジェルネイルでは、ジェルと呼ばれる粘液状の合成樹脂を爪に塗り、LEDライトもしくはUV（紫外線）ライトを数十秒から1分程度照射してジェルを固める。この爪にジェルを塗る作業と照射を繰り返し、ネイルを完成させる。おおむね両手で平均1時間半の時間を要する（リムーブもしくはオフと呼ばれるジェルネイルの取り外しを含める場合は平均2時間程度である）。サービスを提供する際に顧客の要望を聞き、良さに基づき、要望を具体化する。ただし、言葉で伝えるのが難しいという顧客もおり、好きな絵柄やSNS上のネイル写真を持参する場合も多くなっている。またB社の価格体系は表のようになっている（4ページ参照）。

ネイルサロン市場は2000年代に入り需要が伸び、規模が拡大した。近年、成長はやや鈍化したものの、一定の市場規模が存在する。X市の駅から商店街の中心部に向かう途中にも大手チェーンによるネイルサロンが出店している。また自宅サロンと呼ばれる、大手チェーンのネイルサロン勤務経験者が退職後に自宅の一室で個人事業として開業しているサロンも、商店街周辺には多数存在する。


開業当初、B社にはほとんど顧客がいなかった。あるとき、B社社長が、自分の子供の卒業式で着用した和服に合わせてデザインしたジェルネイルの写真を写真共有アプリ上にアップした。その画像がネット上で話題になり拡散され、技術の高さを評価した周辺住民が来店するようになった。そして、初期の顧客が友人達にB社を紹介し、徐々に客数が増かしていった。ジェルネイルは爪の成長に伴い施術から3週間～1か月の間隔での来店が必要になる。つまり固定客を獲得できれば、定期的な来店が見込める。特に初来店の際に、顧客の要望に合ったデザイン、もしくは顧客の期待以上のデザインを提案し、そのデザインに対する評価が高ければ、固定化につながる例も多い。この際には社長やYさんが前の勤務先で培った提案力が生かされた。結果、従業者1人当たり25名前後の固定客を獲得するに至り、繁忙期には稼働率が9割を超える時期も散見されるようになった。なお、顧客の大半は従業者と同世代である。そのうちデザイン重視の顧客と住宅地からの近さ重視の顧客は半数ずつとなっている。後者の場合、オプションを追加する顧客は少なく、力を発揮したい2人としてはやや物足りなく感じている。

B社店舗の近隣には、数年間に小型GMSが閉店しそのままの建物があった。そこを大手デベロッパーが買い取り、2019年11月に小型ショッピングモールとして改装オープンすることが決定した。当初、一層の集客を期待したB社社長であったが、当該モール内への、大手チェーンによる低価格ネイルサロンの出店が明らかになった。B社社長は、これまで自宅から近いことを理由に来店していた顧客が大幅に流出することを予想した。B社社長とYさんは大幅に減少する顧客数を補うための施策について思案したが、良い案も出ず、今後の方針について中小企業診断士に相談することとした。

（注）貸衣裳業界で行われるイベント。百貨店、ホール、ホテル、大学、結婚式場などの大規模な会場で、顧客が会場でサンプルを確認、試着し、気に入ったものがあれば商品を予約することができる。支払いは後日行う。

=== 組織図

=== SWOT分析

=== ビジネスモデル

== 要件

=== システム価値

==== システムコンテキスト

==== 要求モデル

=== システム外部環境

==== ビジネスコンテキスト

==== ビジネスユースケース

==== 業務フロー

==== 利用シーン

==== バリエーション・条件

=== システム境界

==== ユースケース複合図

=== システム

==== 情報モデル

==== 状態モデル
